import { useState } from 'react'
import Link from 'next/link'
import styles from '@/styles/about.module.css'
import Nav from '../components/nav'

export default function About(){
    return(
        <>

<Head>
        <title>Create Next App</title>
        <meta name="author" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <Nav></Nav>


        </>
    )
}

